### ISSUE TITLE
Runbot error while installing Belgian chart of account

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo-extra#56] opened 2015-02-19 10:08 UTC
Hi,

I have a problem when i try to use runbot on a "base" database. If I install accounting and then I try trough the wizard to install the belgian chart of account trough the wizard, i have a CPU time limit exceeded error.

![image](https://cloud.githubusercontent.com/assets/7678583/6264778/3489c480-b827-11e4-9838-867578f2f5d7.png)

**Comment by rim-odoo** [comment] 2015-08-06 12:51
Duplicate of https://github.com/odoo/odoo/issues/5726

**Closed by rim-odoo** 2015-08-06 12:51 UTC
